CREATE TABLE app_user (
 id VARCHAR(36) PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL, company VARCHAR(160) NOT NULL,
 contact VARCHAR(160) NOT NULL, phone VARCHAR(40) NOT NULL DEFAULT '',
 role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN','EXHIBITOR')),
 enabled BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE auth_session (
 token_hash VARCHAR(64) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES app_user(id),
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX auth_session_user_idx ON auth_session(user_id);
CREATE TABLE auth_limit (key_hash VARCHAR(64) PRIMARY KEY, hits INTEGER NOT NULL, started_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE fair (
 id VARCHAR(40) PRIMARY KEY, name VARCHAR(120) NOT NULL,
 published BOOLEAN NOT NULL DEFAULT FALSE, rate NUMERIC(14,2) NOT NULL DEFAULT 0,
 assembly_rate NUMERIC(14,2) NOT NULL DEFAULT 0, fixed_fee NUMERIC(14,2) NOT NULL DEFAULT 0,
 tax_percent NUMERIC(6,2) NOT NULL DEFAULT 0,
 reserve_hours INTEGER NOT NULL DEFAULT 48, offer_hours INTEGER NOT NULL DEFAULT 24,
 terms TEXT NOT NULL DEFAULT '', version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE pavilion (
 id VARCHAR(40) PRIMARY KEY, fair_id VARCHAR(40) NOT NULL REFERENCES fair(id),
 name VARCHAR(120) NOT NULL, image_path VARCHAR(200) NOT NULL,
 clean_path VARCHAR(200) NOT NULL, original_pdf VARCHAR(200) NOT NULL,
 map_width NUMERIC(12,3) NOT NULL, map_height NUMERIC(12,3) NOT NULL,
 reviewed BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE booth (
 id VARCHAR(36) PRIMARY KEY, pavilion_id VARCHAR(40) NOT NULL REFERENCES pavilion(id),
 code VARCHAR(40) NOT NULL, area NUMERIC(12,2), dimensions VARCHAR(160) NOT NULL DEFAULT '',
 geometry TEXT NOT NULL, font_size NUMERIC(6,2) NOT NULL DEFAULT 6,
 label VARCHAR(160) NOT NULL DEFAULT '', status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE'
 CHECK (status IN ('AVAILABLE','RESERVED','CONTRACTED','BLOCKED','ARCHIVED')),
 owner_id VARCHAR(36) REFERENCES app_user(id), expires_at TIMESTAMP WITH TIME ZONE,
 group_id VARCHAR(36), active BOOLEAN NOT NULL DEFAULT TRUE,
 source_geometry TEXT, source_label VARCHAR(160) NOT NULL DEFAULT '',
 verified BOOLEAN NOT NULL DEFAULT FALSE, version BIGINT NOT NULL DEFAULT 0,
 UNIQUE (pavilion_id,code)
);
CREATE INDEX booth_pavilion ON booth(pavilion_id);
CREATE INDEX booth_group ON booth(group_id);
CREATE TABLE queue_entry (
 id VARCHAR(36) PRIMARY KEY, booth_id VARCHAR(36) NOT NULL REFERENCES booth(id),
 user_id VARCHAR(36) NOT NULL REFERENCES app_user(id), joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
 UNIQUE (booth_id,user_id)
);
CREATE INDEX queue_order ON queue_entry(booth_id,joined_at,id);
CREATE TABLE contract_order (
 id VARCHAR(36) PRIMARY KEY, fair_id VARCHAR(40) NOT NULL REFERENCES fair(id),
 user_id VARCHAR(36) NOT NULL REFERENCES app_user(id), booth_ids TEXT NOT NULL,
 snapshot TEXT NOT NULL, total NUMERIC(16,2) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
 accepted_at TIMESTAMP WITH TIME ZONE NOT NULL, acceptance_ip VARCHAR(100) NOT NULL,
 cancelled_at TIMESTAMP WITH TIME ZONE, cancellation_reason VARCHAR(500)
);
CREATE TABLE notification (
 id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES app_user(id),
 message VARCHAR(500) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, seen BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE audit_log (
 id VARCHAR(36) PRIMARY KEY, actor VARCHAR(254) NOT NULL,
 action VARCHAR(80) NOT NULL, target VARCHAR(160) NOT NULL, details TEXT NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE map_annotation (
 id VARCHAR(36) PRIMARY KEY, pavilion_id VARCHAR(40) NOT NULL REFERENCES pavilion(id),
 text VARCHAR(160) NOT NULL, x NUMERIC(12,3) NOT NULL, y NUMERIC(12,3) NOT NULL,
 font_size NUMERIC(6,2) NOT NULL DEFAULT 10, rotation NUMERIC(6,2) NOT NULL DEFAULT 0,
 version BIGINT NOT NULL DEFAULT 0
);
